### PR TITLE
Finalized Settings!

### PR DESCRIPTION
**Pull request by ysunil3**

### CODE REVIEW

**Comment by Cinnamon18** [comment]
hi, thanks for the pr! the settings menu is looking really great! just to clarify, should this pr contain work on the pause menu and the settings menu, or just the settings menu? I just wanted to make sure that the changes to the pause menu were intentional!

also, could you clarify the changes to the message broker? my suspicion is you might've accidentally accepted an older version and thrown out the newer work! but the changes are intentional that's fine, let's just talk them over.

**Comment by ysunil3** [comment]
Sorry I responded so late, this pr should only contain changes to the settings menu. How can I see what changes were made to the pause menu, cuz I didn't change it as far as im aware
________________________________

**Comment by Cinnamon18** [comment]
no worries! you can see the changes at https://github.com/reverienest/Lunacia/pull/20/files on the gui, or there should be a way to do so from git command line by comparing your most recent commit and the first one you did when you started working. in the future you can avoid the extra file changes by not commiting all your files, only the ones you know you worked on!

**Comment by ysunil3** [comment]
So I looked at the changes and I'm not sure how it happened but I seem to have somehow deleted many lines from certain files and deleted some files entirely. Should I just submit a new pull request?
________________________________

**Pull request closed without merging**
