### PR TITLE
Key Bindings Submenu

### PR DESCRIPTION
**Pull request by heatherzhu**
To be added to settings menu

### CODE REVIEW

**Comment by Cinnamon18** [comment]
hi!! thanks so much for the pr! I think this is a really solid foundation, and I like your UI design. do you think you could integrate this with the settings menu scene? just so they're all in one place!

also, sorry, how do i actually rebind the keys? is it just a matter of typing a new value in the text field? if that's the case, you might want to somehow confirm that the new setting has been received!

**Comment by heatherzhu** [comment]
Hey! Our group is planning to meet tomorrow to figure out how to combine everything. To theoretically rebind the key now, you would just type in a new value in the text field, but I didn't know what to actually bind the text fields to right now, so right now it's just the UI. Do you have any advice on how to make the bindings work?

**Comment by Cinnamon18** [comment]
gotcha gotcha. i haven't personally done it before, but why don't you try the suggestions in this thread: https://forum.unity.com/threads/changing-keys-at-runtime.762611/

**Comment by heatherzhu** [comment]
Thanks! I’ll definitely check that out

**Comment by Cinnamon18** [comment]
i just realized!! i totally forgot to mention, check out this documentation too, i think it might be useful: https://docs.unity3d.com/Manual/class-InputManager.html

**Comment by heatherzhu** [comment]
Thanks!

**Pull request closed without merging**
